[workspace]
resolver = "3"
members = ["pipeline"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "BSD-3-Clause"
repository = "https://github.com/kalapowered/kalareach-plugins"
publish = false

[workspace.dependencies]
aws-lc-rs = "=1.18.1"
clap = { version = "=4.6.7", features = ["derive", "env"] }
hex = "=0.4.3"
jiff = "=0.2.37"
kr-plugin-sdk = { git = "https://github.com/kalapowered/kalareach.git", rev = "0c79d9fdd936134e3f44f96973fe7705d3df439d" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
sha2 = "=0.11.0"
tempfile = "=3.27.0"
thiserror = "=2.0.20"
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread", "fs"] }
tough = "=0.24.0"
url = "=2.5.8"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
